// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8glKIdNy746UFzXghcQc1RuAUxpB4ljM',
    appId: '1:164950589062:web:b66332717ce42b29415b07',
    messagingSenderId: '164950589062',
    projectId: 'steel-order-manager',
    authDomain: 'steel-order-manager.firebaseapp.com',
    storageBucket: 'steel-order-manager.firebasestorage.app',
    measurementId: 'G-5W5L7VBTVC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXXKJeNR5E3zMK-46YPd0SSifWCTgvJYs',
    appId: '1:164950589062:android:1f9084f54b94f28d415b07',
    messagingSenderId: '164950589062',
    projectId: 'steel-order-manager',
    storageBucket: 'steel-order-manager.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqBwgfrhtZLJdZRTMI49cYHLBPKvgAlZo',
    appId: '1:164950589062:ios:e3cf207bc3521e63415b07',
    messagingSenderId: '164950589062',
    projectId: 'steel-order-manager',
    storageBucket: 'steel-order-manager.firebasestorage.app',
    iosBundleId: 'com.example.orderManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqBwgfrhtZLJdZRTMI49cYHLBPKvgAlZo',
    appId: '1:164950589062:ios:e3cf207bc3521e63415b07',
    messagingSenderId: '164950589062',
    projectId: 'steel-order-manager',
    storageBucket: 'steel-order-manager.firebasestorage.app',
    iosBundleId: 'com.example.orderManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8glKIdNy746UFzXghcQc1RuAUxpB4ljM',
    appId: '1:164950589062:web:40af55dc6cd662db415b07',
    messagingSenderId: '164950589062',
    projectId: 'steel-order-manager',
    authDomain: 'steel-order-manager.firebaseapp.com',
    storageBucket: 'steel-order-manager.firebasestorage.app',
    measurementId: 'G-MEE0MQEX6Z',
  );
}
